pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git credentialsId: 'Git', url: 'https://github.com/sriarunb/DevopsTestProjects.git'
            }
        }
        stage('PHP Lint Test') {
            steps {
                sh 'find . -name "*.php" -exec php -l {} \\;'
            }
        }
    }
}

