pipeline {
    agent any

    stages {
        
        stage('PHP Lint Test') {
            steps {
                echo 'Checking PHP Syntax Errors...'
                                sh 'find . -name "*.php" -exec php -l {} \\;'
            }
        }
    }
}
